name = "job-shark-api"
main = "src/index.ts"
compatibility_date = "2026-10-09"

[vars]
APP_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "job-shark-db"
database_id = "e0127489-aeca-477d-8487-2b3e85a97eec"
