import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, Bell, BriefcaseBusiness, Check, CheckCircle2, ChevronDown, ExternalLink, FileCheck2, FileText, Filter, Globe2, LayoutDashboard, ListChecks, MapPin, Plus, Pencil, Search, Settings2, ShieldCheck, Sparkles, Target, Trash2, UploadCloud, X } from "lucide-react";

type Status = "Discovered" | "Needs review" | "Approved" | "Submitted" | "Interview" | "Rejected";
type Job = { id:string; title:string; company:string; location:string; type:string; salary:string; source:string; score:number; eligibility:string; skills:string[]; url:string; status:Status; notes?:string; demo?:boolean };
type Profile = { role:string; country:string; workTypes:string; skills:string; cvName:string };
const demoJobs:Job[] = [
{id:"demo-1",title:"Full-Stack Software Engineer",company:"Sample Product Studio",location:"Remote · eligibility unverified",type:"Full-time",salary:"Not listed",source:"Demo record",score:91,eligibility:"Not verified",skills:["React","Next.js","Node.js"],url:"https://example.com",status:"Discovered",demo:true},
{id:"demo-2",title:"Business Systems Automation Specialist",company:"Sample Operations Co.",location:"Remote · check country restrictions",type:"Contract",salary:"Not listed",source:"Demo record",score:84,eligibility:"Check location",skills:["APIs","Automation","Process improvement"],url:"https://example.com",status:"Needs review",demo:true},
{id:"demo-3",title:"Backend Developer",company:"Sample SaaS Team",location:"Remote · eligibility unverified",type:"Full-time",salary:"Not listed",source:"Demo record",score:78,eligibility:"Not verified",skills:["REST APIs","SQL","Node.js"],url:"https://example.com",status:"Discovered",demo:true}
];
const statuses:Status[]=["Discovered","Needs review","Approved","Submitted","Interview","Rejected"];
const defaultProfile:Profile={role:"Full-Stack Developer / Business Systems Developer",country:"Nigeria",workTypes:"Remote, full-time, contract and part-time",skills:"React, Next.js, TypeScript, Node.js, APIs, databases, deployment, AI apps, process improvement",cvName:""};

export default function App(){
const [jobs,setJobs]=useState<Job[]>(demoJobs),[section,setSection]=useState("Overview"),[query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState("All statuses"),[typeFilter,setTypeFilter]=useState("All types"),[filters,setFilters]=useState(false),[addOpen,setAddOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[toast,setToast]=useState(""),[profile,setProfile]=useState<Profile>(defaultProfile);
const [newJob,setNewJob]=useState({title:"",company:"",url:"",location:"Remote",type:"Full-time",salary:"",notes:""}),[editingJobId,setEditingJobId]=useState<string|null>(null);
useEffect(()=>{try{const j=localStorage.getItem("job-shark.jobs"),p=localStorage.getItem("job-shark.profile");if(j)setJobs(JSON.parse(j));if(p)setProfile(JSON.parse(p));}catch{}},[]);
useEffect(()=>{try{localStorage.setItem("job-shark.jobs",JSON.stringify(jobs));}catch{}},[jobs]);
useEffect(()=>{try{localStorage.setItem("job-shark.profile",JSON.stringify(profile));}catch{}},[profile]);
function notify(s:string){setToast(s);window.setTimeout(()=>setToast(""),3000);}
const counts={discovered:jobs.filter(j=>j.status==="Discovered").length,review:jobs.filter(j=>j.status==="Needs review").length,submitted:jobs.filter(j=>j.status==="Submitted").length,interviews:jobs.filter(j=>j.status==="Interview").length};
const visible=useMemo(()=>jobs.filter(j=>{const q=query.toLowerCase();return (!q||[j.title,j.company,j.location,j.notes??"",...j.skills].some(v=>v.toLowerCase().includes(q)))&&(statusFilter==="All statuses"||j.status===statusFilter)&&(typeFilter==="All types"||j.type===typeFilter)&&(section==="Approval queue"?["Needs review","Approved"].includes(j.status):section==="Applications"?["Approved","Submitted","Interview","Rejected"].includes(j.status):true);}),[jobs,query,statusFilter,typeFilter,section]);
function setStatus(id:string,status:Status){setJobs(old=>old.map(j=>j.id===id?{...j,status}:j));notify(status==="Approved"?"Approved for preparation only. Nothing has been submitted.":"Status updated to "+status+".");}
function deleteJob(id:string,title:string){if(!window.confirm(`Delete “${title}” from your tracker? This only removes the saved record; it does not affect any application on a company website.`))return;setJobs(old=>old.filter(j=>j.id!==id));notify("Job removed from your tracker.");}
function openEditJob(j:Job){setEditingJobId(j.id);setNewJob({title:j.title,company:j.company,url:j.url,location:j.location,type:j.type,salary:j.salary,notes:j.notes??""});setAddOpen(true);}
function addJob(e:FormEvent){e.preventDefault();if(!newJob.title.trim()||!newJob.company.trim()||!newJob.url.trim()){notify("Enter a job title, company and URL.");return;}if(editingJobId){setJobs(old=>old.map(j=>j.id===editingJobId?{...j,title:newJob.title.trim(),company:newJob.company.trim(),url:newJob.url.trim(),location:newJob.location||"Not specified",type:newJob.type,salary:newJob.salary||"Not listed",notes:newJob.notes.trim(),source:j.demo?"Demo record":"Edited manually"}:j));setEditingJobId(null);setAddOpen(false);setNewJob({title:"",company:"",url:"",location:"Remote",type:"Full-time",salary:"",notes:""});notify("Job details updated.");return;}const j:Job={id:crypto.randomUUID(),title:newJob.title.trim(),company:newJob.company.trim(),url:newJob.url.trim(),location:newJob.location||"Not specified",type:newJob.type,salary:newJob.salary||"Not listed",notes:newJob.notes.trim(),source:"Added manually",score:0,eligibility:"Not verified",skills:[],status:"Needs review"};setJobs(old=>[j,...old]);setNewJob({title:"",company:"",url:"",location:"Remote",type:"Full-time",salary:""});setAddOpen(false);setSection("Approval queue");notify("Saved to your review queue.");}
function exportCsv(){const rows=[["Title","Company","Location","Type","Salary","Fit score","Eligibility","Status","Notes","URL"],...jobs.map(j=>[j.title,j.company,j.location,j.type,j.salary,String(j.score),j.eligibility,j.status,j.notes??"",j.url])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8;"}));const a=document.createElement("a");a.href=url;a.download="job-shark-tracker.csv";a.click();URL.revokeObjectURL(url);notify("Tracker exported to CSV.");}
const nav=[{label:"Overview",icon:LayoutDashboard},{label:"Discover jobs",icon:Search},{label:"Approval queue",icon:ShieldCheck},{label:"Applications",icon:ListChecks},{label:"My profile",icon:Settings2}];
return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-icon"><Sparkles size={20}/></div><div><b>Job-Shark</b><small>CAREER AUTOMATION</small></div></div><div className="side-label">WORKSPACE</div><nav>{nav.map(n=>{const I=n.icon;return <button key={n.label} className={"nav-item "+(section===n.label?"active":"")} onClick={()=>{setSection(n.label);if(n.label==="My profile")setProfileOpen(true);}}><I size={18}/><span>{n.label}</span>{n.label==="Approval queue"&&counts.review>0&&<em>{counts.review}</em>}</button>})}</nav><div className="side-bottom"><div className="privacy"><ShieldCheck size={19}/><b>You stay in control</b><p>Every application waits for your review. No final submission automation is enabled.</p></div><div className="user"><div className="avatar">JS</div><div><b>Job seeker</b><small>Personal workspace</small></div><button className="icon-btn" onClick={()=>setProfileOpen(true)} aria-label="Edit profile"><Settings2 size={16}/></button></div></div></aside>
<main className="main"><header className="topbar"><div className="crumb">Workspace <span>/</span><b>{section}</b></div><div className="top-actions"><span className="local-pill"><i/> Local preview</span><button className="icon-btn" onClick={()=>notify("No new notifications.")} aria-label="Notifications"><Bell size={18}/></button><button className="icon-btn" onClick={()=>setProfileOpen(true)} aria-label="Profile"><Settings2 size={18}/></button></div></header>
<div className="content"><div className="page-head"><div><div className="eyebrow">JOB SEARCH / PERSONAL WORKSPACE</div><h1>{section==="Overview"?"Your career workspace":section}</h1><p>{section==="Overview"?"A more organised way to find your next opportunity.":section==="Discover jobs"?"Review roles and save opportunities worth pursuing.":section==="Approval queue"?"Verify each role before preparing an application.":section==="Applications"?"Track application progress in one place.":"Set preferences for future eligibility screening."}</p></div><div className="head-actions"><button className="btn secondary" onClick={exportCsv}><FileText size={15}/> Export tracker</button><button className="btn primary" onClick={()=>{setEditingJobId(null);setNewJob({title:"",company:"",url:"",location:"Remote",type:"Full-time",salary:""});setAddOpen(true);}}><Plus size={16}/> Add a job</button></div></div>
{section==="Overview"&&<><section className="hero"><div className="hero-symbol"><Sparkles size={22}/></div><div className="hero-copy"><span>YOUR NEXT OPPORTUNITY STARTS HERE</span><h2>Make your job search work smarter.</h2><p>Discover roles, check your fit, and keep every application accountable.</p></div><div className="hero-art"><div className="orb orb1"/><div className="orb orb2"/><div className="float-chip chip1"><CheckCircle2 size={14}/> Review before applying</div><div className="float-chip chip2"><FileCheck2 size={14}/> Track every step</div></div></section><section className="stats"><Stat label="Jobs discovered" value={counts.discovered} hint="In your job list" icon={<Search size={18}/>} tone="blue"/><Stat label="Awaiting review" value={counts.review} hint="Your decision needed" icon={<ShieldCheck size={18}/>} tone="amber"/><Stat label="Applications submitted" value={counts.submitted} hint="Tracker status only" icon={<FileCheck2 size={18}/>} tone="green"/><Stat label="Interviews" value={counts.interviews} hint="Keep the momentum" icon={<Activity size={18}/>} tone="purple"/></section></>}
<div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search job title, company or skill..."/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear search"><X size={14}/></button>}</div><button className="btn secondary" onClick={()=>setFilters(v=>!v)}><Filter size={15}/> Filters <ChevronDown size={14}/></button><span className="result-count">{visible.length} records</span></div>
{filters&&<div className="filter-panel"><label>Status<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Work type<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option>All types</option><option>Full-time</option><option>Contract</option><option>Part-time</option><option>Internship</option></select></label><button className="text-btn" onClick={()=>{setStatusFilter("All statuses");setTypeFilter("All types");setQuery("");}}>Clear filters</button></div>}
<section className="panel"><div className="panel-head"><div><h2>{section==="Approval queue"?"Approval queue":section==="Applications"?"Application tracker":section==="Discover jobs"?"Job opportunities":"Recent opportunities"}</h2><p>Sample records are for testing only, not verified vacancies.</p></div><span className="record-tag">{visible.length} RECORDS</span></div>{visible.length===0?<div className="empty"><Search size={24}/><h3>No matching jobs</h3><p>Adjust your filters or add a job link to begin.</p><button className="btn primary" onClick={()=>setAddOpen(true)}><Plus size={15}/> Add a job</button></div>:<div className="job-list">{visible.map(j=><article className="job-row" key={j.id}><div className="company-mark">{j.company.split(/\s+/).map(w=>w[0]).join("").slice(0,2).toUpperCase()}</div><div className="job-info"><div className="job-title"><h3>{j.title}</h3><span className={"status status-"+j.status.toLowerCase().replaceAll(" ","-")}>{j.status}</span></div><div className="company-line">{j.company}<span>·</span><MapPin size={13}/>{j.location}</div><div className="job-meta"><span><BriefcaseBusiness size={13}/>{j.type}</span><span><Globe2 size={13}/>{j.source}</span><span><ShieldCheck size={13}/>{j.eligibility}</span></div>{j.skills.length>0&&<div className="tags">{j.skills.map(s=><span key={s}>{s}</span>)}</div>}{j.notes&&<div className="demo-note">Notes: {j.notes}</div>}{j.demo&&<div className="demo-note">Demo only — replace with a real, verified listing.</div>}</div><div className="score"><span>FIT SCORE</span><b className={j.score>=85?"high":j.score>=70?"mid":"low"}>{j.score?j.score+"%":"—"}</b><small>{j.score?"Illustrative":"Not scored"}</small></div><div className="row-actions"><a className="icon-btn link" href={j.url} target="_blank" rel="noreferrer" title="Open job listing"><ExternalLink size={15}/></a><button className="icon-btn" onClick={()=>openEditJob(j)} aria-label={"Edit "+j.title} title="Edit job"><Pencil size={15}/></button><button className="icon-btn" onClick={()=>deleteJob(j.id,j.title)} aria-label={"Delete "+j.title} title="Delete job"><Trash2 size={15}/></button><select aria-label={"Status for "+j.title} value={j.status} onChange={e=>setStatus(j.id,e.target.value as Status)}>{statuses.map(s=><option key={s}>{s}</option>)}</select>{j.status==="Needs review"&&<button className="approve" onClick={()=>setStatus(j.id,"Approved")}><Check size={14}/> Approve</button>}</div></article>)}</div>}<div className="panel-foot"><span><i/> Demo data only · no live feed connected yet</span><span>Saved in this browser</span></div></section>
<div className="lower-grid"><section className="panel lower"><div className="lower-head"><div className="lower-icon blue"><Target size={17}/></div><div><h3>Build your workflow</h3><p>What we will connect next</p></div></div><ul className="next-list"><li><span>1</span>Confirm job preferences <button onClick={()=>setProfileOpen(true)}>Edit</button></li><li><span>2</span>Add your CV details <button onClick={()=>setProfileOpen(true)}>Add CV</button></li><li><span>3</span>Connect verified job sources <em>Next phase</em></li><li><span>4</span>Guided form filling and approval <em>Next phase</em></li></ul></section><section className="panel lower"><div className="lower-head"><div className="lower-icon purple"><Activity size={17}/></div><div><h3>Application pipeline</h3><p>Current record statuses</p></div></div><div className="pipeline">{(["Discovered","Needs review","Approved","Submitted"] as Status[]).map((s,i)=>{const n=jobs.filter(j=>j.status===s).length;return <div className="pipeline-row" key={s}><span>{s}</span><div className="track"><i className={"fill fill-"+i} style={{width:(jobs.length?Math.max(n/jobs.length*100,n?7:0):0)+"%"}}/></div><b>{n}</b></div>})}</div></section></div><footer className="footer"><span>Job-Shark · Personal job-search workspace</span><span><ShieldCheck size={13}/> Human approval required before submission</span></footer>
</div></main>
{addOpen&&<div className="backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAddOpen(false)}}><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><div className="eyebrow">JOB INTAKE</div><h2>{editingJobId?"Edit job opportunity":"Add a job opportunity"}</h2><p>{editingJobId?"Update the details saved in your tracker.":"Save a job link for screening and review."}</p></div><button className="icon-btn" onClick={()=>{setAddOpen(false);setEditingJobId(null);}} aria-label="Close"><X size={18}/></button></div><form onSubmit={addJob}><label>Job title *<input required value={newJob.title} onChange={e=>setNewJob({...newJob,title:e.target.value})} placeholder="e.g. Full-Stack Engineer"/></label><label>Company *<input required value={newJob.company} onChange={e=>setNewJob({...newJob,company:e.target.value})} placeholder="Company name"/></label><label>Job URL *<input required type="url" value={newJob.url} onChange={e=>setNewJob({...newJob,url:e.target.value})} placeholder="https://company.com/careers/role"/></label><div className="form-grid"><label>Location<input value={newJob.location} onChange={e=>setNewJob({...newJob,location:e.target.value})}/></label><label>Work type<select value={newJob.type} onChange={e=>setNewJob({...newJob,type:e.target.value})}><option>Full-time</option><option>Contract</option><option>Part-time</option><option>Internship</option></select></label></div><label>Salary (optional)<input value={newJob.salary} onChange={e=>setNewJob({...newJob,salary:e.target.value})} placeholder="Salary or not listed"/></label><label>Notes (optional)<textarea rows={3} value={newJob.notes} onChange={e=>setNewJob({...newJob,notes:e.target.value})} placeholder="Eligibility details, recruiter contact, application deadline, or next steps"/></label><div className="modal-note"><ShieldCheck size={16}/> New records are unverified and enter review. Adding a job never submits an application.</div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>{setAddOpen(false);setEditingJobId(null);}}>Cancel</button><button type="submit" className="btn primary">{editingJobId?<><Check size={15}/> Save changes</>:<><Plus size={15}/> Add to review queue</>}</button></div></form></section></div>}
{profileOpen&&<div className="backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setProfileOpen(false)}}><section className="modal profile-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><div className="eyebrow">PERSONALISATION</div><h2>Your job profile</h2><p>Preferences for future eligibility screening.</p></div><button className="icon-btn" onClick={()=>setProfileOpen(false)} aria-label="Close"><X size={18}/></button></div><form onSubmit={e=>{e.preventDefault();setProfileOpen(false);notify("Profile saved in this browser.");}}><label>Target role<input value={profile.role} onChange={e=>setProfile({...profile,role:e.target.value})}/></label><div className="form-grid"><label>Home country<input value={profile.country} onChange={e=>setProfile({...profile,country:e.target.value})}/></label><label>Work preferences<input value={profile.workTypes} onChange={e=>setProfile({...profile,workTypes:e.target.value})}/></label></div><label>Skills (comma-separated)<textarea rows={3} value={profile.skills} onChange={e=>setProfile({...profile,skills:e.target.value})}/></label><label>CV file name or path<input value={profile.cvName} onChange={e=>setProfile({...profile,cvName:e.target.value})} placeholder="CV.pdf (uploads added later)"/></label><div className="modal-note"><UploadCloud size={16}/> This stores profile preferences only. Secure CV storage and real form uploads are a later phase.</div><div className="modal-actions"><button type="button" className="btn secondary" onClick={()=>setProfileOpen(false)}>Cancel</button><button type="submit" className="btn primary"><Check size={15}/> Save profile</button></div></form></section></div>}
{toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}<button onClick={()=>setToast("")} aria-label="Dismiss"><X size={14}/></button></div>}
</div>;
}
function Stat(p:{label:string;value:number;hint:string;icon:React.ReactNode;tone:string}){return <div className="stat"><div className={"stat-icon "+p.tone}>{p.icon}</div><span>{p.label}</span><div className="stat-bottom"><b>{p.value}</b><small>{p.hint}</small></div></div>;}
